CHANGELOG.md
CODE_OF_CONDUCT.md
LICENSE
MANIFEST.in
README.md
setup.cfg

- Updated readme based on comments from pysatCDAAC.
- Adds manifest for pypi integration. Test package successfully uploaded. https://test.pypi.org/project/pysatNASA/0.0.1/
- Updates metadata config info

v0.0.1 release

---

pysatNASA/tests/test_instruments.py

Updates style for instrument tests according to pysat/pysat#569

STY: update tests for consistency across projects

---

pysatNASA/instruments/methods/cdaweb.py

Improved the load method such that all filenames passed in are now supported. Tests will be expanded over in pysat core.

ENH: Load all supplied filenames

---

pysatNASA/instruments/__init__.py
pysatNASA/instruments/formosat1_ivm.py

Addresses #2.  Renames 'rocsat1' as 'formosat1' in keeping with community conventions.

STY: Formosat update

---

pysatNASA/instruments/icon_euv.py
pysatNASA/instruments/icon_fuv.py
pysatNASA/instruments/icon_mighti.py
pysatNASA/instruments/methods/icon.py

Updates ICON data paths to accomodate zip files on FTP server.
Once files are migrated over to SPDF, this will be replaced by the standard cdaweb routines.

BUG: ICON data paths

---

pysatNASA/instruments/ses14_gold.py

Restoring support for the cycle keyword in gold data

ENH: support cycle

---

pysatNASA/constellations/__init__.py
pysatNASA/constellations/de2.py
pysatNASA/constellations/icon.py

Fixed the constellation objects.  Depends on pysat PR https://github.com/pysat/pysat/pull/669.

BUG: Fix constellations

---

.travis.yml
pysatNASA/instruments/icon_ivm.py
pysatNASA/instruments/methods/cdaweb.py

Addresses #54 
Corrects the ion drift cleaning along magnetic basis directions to use flags from both the RPA and DM.

BUG: Corrected cleaning drifts magnetic directions.

---

.travis.yml
pysatNASA/instruments/methods/cdaweb.py

Uses the testpypi install for pysat 3.0 release candidate.  Will be replaced once 3.0.0 is release.

MAINT: pysat 3.0.0 test update

---

.github/workflows/docs.yml
.github/workflows/main.yml
CONTRIBUTING.md

- Updates the GA workflows for consistency in style, ease of future upgrades.
- Fixes a broken link in the docs now that pysat 3.0.0 is out

STY: update standards

---

CONTRIBUTING.md
pysatNASA/instruments/icon_mighti.py

Reduces code duplication and code complexity in the MIGHTI clean routines

STY: mighti clean updates

---

docs/index.rst
docs/migration_guide.rst

Addresses #50.
Adds migration guide to the docs for users of previous versions.
tested via local build and inspection of documents

DOC: Migration Guide

---

pysatNASA/instruments/omni_hro.py
pysatNASA/tests/test_omni_hro.py

Addresses #74.
test with develop branch of pysat
```
pytest -vs pysatNASA/tests/test_omni_hro.py::TestOMNICustom
```

BUG: fix omni imf steadiness for new pysat

---

.github/workflows/docs.yml
.github/workflows/main.yml
CHANGELOG.md
pysat_requirements.txt
requirements.txt

Addresses pysat/pysat#821
- Adds windows testing to Github Actions
- Updates NEP29 minimum numpy in tests to 1.18.0
Adjustments to Github Actions environment, tested there.
* Operating system: ubuntu and Windows
* Version number: python 3.7, 3.8, 3.9

TST: add windows tests

---

CHANGELOG.md
pysatNASA/instruments/templates/template_cdaweb_instrument.py

Addresses #63
Updates the template and documentation to be consistent with pysat standards.
visual inspection

MAINT: update template instrument

---

CHANGELOG.md

Updates changelog version numbers.  0.0.3 not yet released!
The usual way.

BUG: fix changelog for 0.0.3

---

.github/workflows/docs.yml
.github/workflows/main.yml
CHANGELOG.md
pysatNASA/instruments/timed_saber.py

TIMED SABER released a new version of data, and the filenames and directories have changed.  Updates to use the latest.
Also updates github actions python version to 3.
Standard tests.  Since remote location and filename have changed, files will not download with old code.
* Operating system: Mac OS X Monterrey
* Version number: Python 3.8.11

BUG/MAINT:  TIMED SABER version and github actions

---

.github/workflows/main.yml
.github/workflows/pysat_rc.yml
CHANGELOG.md

Addresses ROADMAP
Adds an additional workflow to download pysat from test.pypi for integration testing with future pysat releases.  Workflow is manually triggered (button will appear when merged into main).  Pushing this forward now since we are about to relase new code.
Setting to push and inspecting the logs at https://github.com/pysat/pysatNASA/actions/runs/3346690449 to ensure that the correct things are installed.
* Operating system: Mac and Windows
* Version number: Python 3.10
* Github Actions

TST: add workflow_dispatch action to test pysatNASA with latest pysat RC

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md
.github/workflows/docs.yml
.github/workflows/main.yml
.github/workflows/pysat_rc.yml
CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md
docs/conf.py

Addresses #143 
Updates according to [uniform standards](https://github.com/pysat/pysatEcosystem_Template/pull/6)
NOTE: keeping as draft until other packages are scanned.
with `diff`!

STY: update templates

---

.github/workflows/docs.yml
.github/workflows/pip_rc_install.yml
.github/workflows/pysat_rc.yml
CHANGELOG.md

Adds a new workflow to  install the RC through the test pypi server for each major operating system.  Designed to catch any issues that may stem from improper local build and upload.
Github Actions

TST: manual workflow to install latest RC from test pypi

---

CHANGELOG.md
pysatNASA/constellations/de2.py
pysatNASA/constellations/icon.py

Addresses #152
Updates docstrings to explain that data is not expected for both IVM instruments on any given day.
Inspection

DOC: ICON constellation info

---

CHANGELOG.md
pysatNASA/instruments/ace_epam_l2.py
pysatNASA/instruments/ace_mag_l2.py
pysatNASA/instruments/ace_sis_l2.py
pysatNASA/instruments/ace_swepam_l2.py
pysatNASA/instruments/cnofs_plp.py
pysatNASA/instruments/de2_fpi.py
pysatNASA/instruments/de2_lang.py
pysatNASA/instruments/de2_nacs.py
pysatNASA/instruments/de2_rpa.py
pysatNASA/instruments/de2_vefi.py
pysatNASA/instruments/de2_wats.py
pysatNASA/instruments/formosat1_ivm.py
pysatNASA/instruments/igs_gps.py
pysatNASA/instruments/iss_fpmu.py
pysatNASA/instruments/jpl_gps.py
pysatNASA/instruments/methods/ace.py
pysatNASA/instruments/methods/general.py

Addresses #187
The ACE clean routine (which was based on the PLP clean routine) is moved to general methods, and applied to a number of historical instruments.  
Loading clean and non-clean files to compare meta.
* Operating system: Moneterrey
* Version number: Python 3.10.9

ENH: Use generalized clean function

---

CHANGELOG.md
pysatNASA/instruments/methods/_cdf.py
pysatNASA/instruments/methods/ace.py
pysatNASA/tests/test_instruments.py

Addresses #176 
When loading a dataset into a pandas dataframe header level metadata was not being attached.
- Bug fix
- Local pytest
- Manual check
* Operating system: [MacOS 13.4]
* Version number: [Python 3.9]
* conda environment

Header meta

---

CHANGELOG.md
pysatNASA/instruments/icon_fuv.py
pysatNASA/instruments/methods/general.py
pysatNASA/instruments/methods/icon.py
pysatNASA/instruments/ses14_gold.py
pysatNASA/instruments/timed_guvi.py
pysatNASA/instruments/timed_saber.py
pysatNASA/instruments/timed_see.py

Updates test flags for the warnings raised when clean is not implemented in preaparation for https://github.com/pysat/pysat/pull/1129
with the pysat branch for https://github.com/pysat/pysat/pull/1129

TST: clean warnings

---

CHANGELOG.md
docs/index.rst
pysatNASA/instruments/dmsp_ssusi.py
pysatNASA/instruments/methods/jhuapl.py
pysatNASA/instruments/timed_guvi.py
pysatNASA/tests/test_methods_jhuapl.py

Adds new data tags to the DMSP SSUSI instrument and fixes bugs in the TIMED GUVI cleaning method.
```
import pysat
stime = dt.datetime(2015, 1, 1)
dmsp = pysat.Instrument(inst_module=pysatNASA.instruments.dmsp_ssusi, tag='sdr-disk', inst_id='f16')
dmsp.download(start=stime)
dmsp.load(date=stime)
```
Also added unit tests for some of the JHUAPL functions, including the new cleaning function.
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant: RC branch of pysat …

ENH: DMSP SSUSI SDR disk images
