.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .zenodo.json, CONTRIBUTING.md
Addresses #5 
Adds github templates for issues and pull requests.  Based on the versions at pysat, with a few additions for the examples.
=> DOC: add issue and PR templates, zenodo.json, contributing

CONTRIBUTING.md, pysatNASA/tests/test_instruments.py
Updates syntax for instrument tests inherited from `pysat` as part of pysat/pysat#552.
- End-to-end instrument tests now iterate over a list of `dict` objects containing info to create an instrument
- `pytest.mark` statements updated accordingly
- `package` renamed as `inst_loc`
Currently failing on Travis since these updates are not in `pysat` develop-3, but passes locally when using the tst/inst_test_class_update branch of `pysat` (with the exception of known ftp issues, ie, #8).
=> MAINT: instrument test updates

README.md, pysatNASA/constellations/icon.py, pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/cnofs_vefi.py, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/iss_fpmu.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/methods/icon.py, pysatNASA/instruments/omni_hro.py, pysatNASA/instruments/rocsat1_ivm.py, pysatNASA/instruments/sport_ivm.py, pysatNASA/instruments/templates/template_cdaweb_instrument.py, pysatNASA/instruments/timed_saber.py, pysatNASA/instruments/timed_see.py, pysatNASA/tests/test_methods_cdaweb.py, pysatNASA/tests/test_omni_hro.py
Addresses pysat/pysat#473, test with pysat/pysat#556
Updates use of `sat_id` to `inst_id`.
Passing locally with the `break/inst_id` branch of pysat.  Expected to fail on Travis until pysat/pysat#556 is merged.
=> MAINT: update sat_id to inst_id

pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/methods/icon.py
Addresses #8.
ICON IVM files currently being stored as zip files on the remote data server.  This adjusts the download tags to search for zip files in the new location, while maintaining netCDF4 as the primary file name. Adds a generalized check to `icon.ssl_download` to automatically unzip zip files and pull the data out to the appropriate directory, removing the zip file afterward.
Tests are compatible with end-to-end tests if run locally (skipped on Travis CI).  The develop branch fails locally, this branch passes.
Simple test script:
```
import pysat
ivm = pysat.Instrument(inst_module=pysatNASA.instruments.icon_ivm, inst_id='a')
ivm.download(dt.datetime(2020, 2, 1), dt.datetime(2020, 2, 28))
ivm.files.files
```
=> ENH: include support for extraction from zip files in ssl_dowload

pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/cnofs_vefi.py, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/formosat1_ivm.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/iss_fpmu.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/methods/icon.py, pysatNASA/instruments/omni_hro.py, pysatNASA/instruments/rocsat1_ivm.py, pysatNASA/instruments/sport_ivm.py, pysatNASA/instruments/templates/template_cdaweb_instrument.py, pysatNASA/instruments/timed_saber.py, pysatNASA/instruments/timed_see.py, pysatNASA/tests/test_methods_cdaweb.py
This pull streamlines the cdaweb download routine.
- Removes separate routines for the multi_file_day instruments
- Reduce custom instrument name and directory strings to two
Old code 
- Workflow
- Ask the server what files are available
- Decide how many loops to iterate based on `multi_file_day`
- Iterate over years, months, etc to individually construct filenames using `.format`
- Uses 'dir', 'remote_fname', 'local_fname' as part of `supported_tags`
- Has the capability of renaming files locally, but politely asks users to keep the same file names
- Included both `remote_site` and `remote_url` variables
- `supported_tags` an arg in `download`, kwarg in `list_remote_files`
New code
- Workflow
- Ask the server what files are available
- Iterate over that list to download files, using …
=> STY: streamline cdaweb download, variable consistency, version support

README.md
Updates the front page to point to the travis-ci.com badges.  Travis plans to finish migrating to the new site by Dec 31, 2020.
=> DOC: use travis-ci.com

.travis.yml, pysatNASA/instruments/ses14_gold.py
Fixing the tags for ses14_gold.  Trying to load the gold instrument manually into pysat produced an error:
```
In [11]: nmax = pysat.Instrument(inst_module=pysatNASA.instruments.ses14_gold, tag='nmax', strict_time_flag=False)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/code/core/pysat/pysat/instruments/methods/general.py in list_files(tag, inst_id, data_path, format_str, supported_tags, fake_daily_files_from_monthly, two_digit_year_break, delimiter)
82         try:
---> 83             format_str = supported_tags[inst_id][tag]
84         except KeyError as kerr:
KeyError: 'nmax'
During handling of the above exception, another exception occurred:
ValueError …
```
=> BUG: update GOLD NMAX tags

CHANGELOG.md, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/omni_hro.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/instruments/timed_see.py
Changed `fake_daily_files_from_monthly` kwarg to `fille_cadance`, which provides more adaptive instrument support.  Also fixed some bugs in OMNI HRO and removed unused kwargs in cdaweb routines.  Requires pysat PR https://github.com/pysat/pysat/pull/629
=> Update to use `file_cadance` kwarg

pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py
Changed name of Instrument method `default` to `preprocess` in accordance with new pysat standards (PR https://github.com/pysat/pysat/pull/626).
Will need the pysat PR to be merged and #26 to be merged before tests will pass.
=> STY: changed name of default to preprocess

pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/tests/test_instruments.py
See issue: https://github.com/pysat/pysat/issues/566
```
In [1]: import datetime as dt 
...: import pysat 
...: import pysatNASA 
...: nmax = pysat.Instrument(inst_module=pysatNASA.instruments.ses14_gold, 
...:                         strict_time_flag=False, tag='nmax')                                                                                                                                                          
pysat WARNING: Time stamps may be non-unique because Channel A and B are different instruments.  An upgrade to the pysat.Constellation object is required to solve this issue. See pysat issue #614 for more info.
In [2]: nmax.remote_file_list(start=dt.datetime(2020, 3, 1), stop=dt.datetime(2020, 3, 31)) …
```
=> BUG: Addresses issue with remote file names

pysatNASA/tests/test_instruments.py
Makes package consistent with https://github.com/pysat/pysat/pull/637.
pysatNASA unit tests pass locally.
=> ENH: Update to latest pysat standards

pysatNASA/instruments/methods/cdaweb.py
Review of test logs in pysat v2.3 revealed:
```
ResourceWarning: Enable tracemalloc to get the object allocation traceback
1733/home/travis/build/pysat/pysat/pysat/instruments/methods/nasa_cdaweb.py:339: ResourceWarning: unclosed file <_io.BufferedWriter name='/tmp/tmpe4lbgacq/timed/saber/timed_l2av207_saber_201901010209_v01.cdf'>
1734  open(saved_local_fname, 'wb').write(req.content)
1735
```
I added a with statement to the open command to ensure the file is closed.
=> BUG: Added with statement to file open

CHANGELOG.md, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/tests/test_methods_cdaweb.py
Addresses #51.
When the start/stop notation was added to `remote_file_list`, the url to search was not updated to include the subdirectory.  The code would then search the front page of cdaweb for files and fail. Note this affects a number of other functions that call this, including `remote_date_range` and `download_updated_files`.  
The end-to-end unit tests from pysat only check this with the start/stop date option.  Since this affects custom code, a test is added to call on plp data (chosen as the data set is fairly small).
=> BUG: remote_file_list for unspecified start/stop dates

pysatNASA/instruments/methods/cdaweb.py
Addresses #68 
Improves download robustness by ensuring that requests closes each connection. Multiple calls to download in a short timeframe can result in requests reusing a connection but then SSL gets out of sync.
=> BUG: SSL Download Issue

pysatNASA/constellations/__init__.py, pysatNASA/constellations/de2.py, pysatNASA/constellations/icon.py, pysatNASA/instruments/__init__.py, pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/cnofs_vefi.py, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/formosat1_ivm.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/iss_fpmu.py, pysatNASA/instruments/methods/_cdf.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/omni_hro.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/instruments/templates/template_cdaweb_instrument.py, pysatNASA/instruments/timed_saber.py, pysatNASA/instruments/timed_see.py, pysatNASA/tests/test_instruments.py, setup.py
Updates docstring style and import order in preparation for flake8-docstrings and hacking tests.
Following pull will be the instrument library docstrings, where the bulk of the changes are.
Local run of flake8.
* Operating system: Mac OS X 10.15.7
* Version number: Python 3.8.2
* `flake8-docstrings` and `hacking`
- [na] Add a note to ``CHANGELOG.md``, summarizing the changes (will update with final pull)
- [na] Update zenodo.json file for new code contributors
=> STY: docstrings and core code (2 of 3)

.github/workflows/main.yml, CHANGELOG.md, pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/cnofs_vefi.py, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/formosat1_ivm.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/iss_fpmu.py, pysatNASA/instruments/methods/__init__.py, pysatNASA/instruments/methods/_cdf.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/methods/cnofs.py, pysatNASA/instruments/methods/de2.py, pysatNASA/instruments/methods/gold.py, pysatNASA/instruments/methods/icon.py, pysatNASA/instruments/omni_hro.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/instruments/timed_saber.py, pysatNASA/instruments/timed_see.py, test_requirements.txt
Updates docstring style and import order in preparation for flake8-docstrings and hacking tests.
Adds `flake8-docstrings` and `hacking` to CI test environment.
Local run of flake8.
* Operating system: Mac OS X 10.15.7
* Version number: Python 3.8.2
* `flake8-docstrings` and `hacking`
- [na] Update zenodo.json file for new code contributors
=> DOC/STY: docstrings for instrument modules (3 of 3)

CHANGELOG.md, pysatNASA/instruments/icon_ivm.py
Addresses #87
ICON IVM data files are slightly misaligned with UT, including about 30s of the previous day and dropping the last 30s.  The `multi_file_day` option corrects for this and allows one complete day to be loaded when requested.
Assuming registration and download,
```
import pysat
ivm = pysat.Instrument('icon', 'ivm', inst_id='a')
ivm.load(2020, 1)
```
Inspection of data should align with day boundaries.
* Operating system: Mac OS X 10.15.7
* Version number: python 3.8.11
- [na] Update zenodo.json file for new code contributors
=> ENH: use `multi_file_day` = True for ICON IVM data

CHANGELOG.md, pysatNASA/constellations/__init__.py, pysatNASA/instruments/__init__.py
Currently dummy variables are used as part of the import process for instruments and constellations.  This removes those so a random string is not attached to the package
To inspect modules and attrs attached, use tab:
```
import pysaNASA
pysatNASA.instruments.[tab]
```
Should only be a list of modules.
* Operating system: Mac OS X 10.15.7
* Version number: python 3.8.11
- [na] Update zenodo.json file for new code contributors
=> STY: clean up imports in package

test_requirements.txt
Coveralls 3.3 is failing on github actions across platforms.  Limiting install to see if something in the new version is at fault.
https://github.com/TheKevJames/coveralls-python/releases
If this successfully runs on Github Actions, it works.
Github Actions
=> BUG: limit coveralls version

CHANGELOG.md, pysatNASA/instruments/omni_hro.py, test_requirements.txt
Inelegantly addresses #95 by altering the meta data in the load routine.
```
import pysat
omni = pysat.Instrument('omni', 'hro', '1min')
omni.load(2020, 102)
omni.meta['SYM_D']
```
Produces:
```
FIELDNAM                                              SYM/D index
SCALEMIN                                                    -1000
SCALEMAX                                                     1000
VAR_TYPE                                                     data
FORMAT                                                         I5
DEPEND_0                                                    Epoch
LABLAXIS                                              SYM/D index
DISPLAY_TYPE …
```
=> Omni quickfix meta

.github/workflows/main.yml, CHANGELOG.md, test_requirements.txt
Updates compliance for NEP29 (dropping tests for python 3.7, numpy 1.18) and pip 22 (limits versions of `hacking` to check).
Update to Github Actions environment.  Tested there.
=> MAINT: update for NEP29, pip 22

CHANGELOG.md, docs/installation.rst, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/omni_hro.py, requirements.txt, setup.cfg
Addresses #111
The version cap for cdflib was employed to avoid bugs and incompatibilities in that version, which have been since fixed.  This accepts only newer versions.
The new version of cdflib avoids the issue with metadata stored in arrays.  The workarounds for meta have been removed.
```
import pysat
plp = pysat.Instrument('cnofs', 'plp')
plp.load(2009, 1)
```
Data should successfully load.
* Operating system: Mac OS X 11.6.5
* Version number: Python 3.8.11
* cdflib 0.4.4
=> MAINT: update cdflib standards for 0.4+

CONTRIBUTING.md, docs/develop_guide/contributing.rst, docs/examples/ex_init.rst, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/instruments/templates/template_cdaweb_instrument.py, pysatNASA/instruments/timed_saber.py, test_requirements.txt
Addresses #106
Fixes the formatting of the contributing doc for RTD.  Updates some info on the contributing page based on the latest pysat develop branch.
Minor formatting updates for the ICON EUV docstring and example code.
Inspection of the build page at RTD:
https://pysatnasa.readthedocs.io/en/sty-rtd/develop_guide/contributing.html
Also at the github level: https://github.com/pysat/pysatNASA/blob/sty/rtd/CONTRIBUTING.md
=> DOC/STY: formatting contributing page in docs

CHANGELOG.md, pysatNASA/constellations/__init__.py, pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/cnofs_vefi.py, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/formosat1_ivm.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/methods/__init__.py, pysatNASA/instruments/methods/general.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/instruments/timed_saber.py, pysatNASA/instruments/timed_see.py
Addresses #89, #118
Adds two general instrument methods which are frequently repeated:
- `init`, where the initialization routine reads from a standard mission-level module (cnofs, de2, icon)
- `clean_warn`, a custom clean routine that warns users that cleaning is not available
Additionally, suppresses logger messages during package-level imports of constellation objects.  This is required to keep the logger from being saturated until this issue is fixed at the pysat-level.  Otherwise verifying the logger here is near-impossible.
```
import pysat
import logging
pysat.logger.setLevel(logging.INFO)
ivm = pysat.Instrument('cnofs', 'ivm')
```
acknowledgement string should go to …
=> STY: reduce duplication for init and clean

setup.cfg
Tidy up after #85.  New custom mark needed to be added to setup.cfg.  Noticed this while inspecting warnings in #100.
Via pytest
* Github actions
=> MAINT: add new custom mark

CHANGELOG.md, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/methods/cdaweb.py
Addresses FutureWarnings from pandas.
Removes deprecated commands from pysat.  New pysat limits from other pulls means we no longer need backwards compatibility for these functions.
inspecting tests and looking for warnings
Loading icon data to verify that time is in a datetime format.
* Operating system: all (GA)
* Version number: Python 3.8, 3.9, 3.10]
=> MAINT: pandas and pysat deprecated syntax

CHANGELOG.md, requirements.txt
The cdf interface doesn't like numpy 1.24.0.  I see some issues with both cdflib and pysatCDF.  Adds a version cap here to fix this for the time being.
Specific failures documented at #142 and https://github.com/pysat/pysatCDF/issues/46
Github Actions and local tests.
Github Actions suite.
=> STY: version cap on numpy

CHANGELOG.md, docs/supported_instruments.rst, pysatNASA/instruments/__init__.py, pysatNASA/instruments/dmsp_ssusi.py, pysatNASA/instruments/methods/__init__.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/methods/dmsp.py, pysatNASA/tests/test_methods_dmsp.py
Added a new instrument for the DMSP SSUSI EDR-Aurora data.  While adding this instrument support, discovered a bug in the general CDAWeb functions.
```
import matplotlib.pyplot as plt
import pysat
ssusi = pysat.Instrument(inst_module=pysatNASA.instruments.dmsp_ssusi, tag='edr-aurora', inst_id='f17')
ssusi.download(start=dt.datetime(2015, 1, 1))
ssusi.load(date=dt.datetime(2015, 1, 1))
fig = plt.figure()
axs = fig.add_subplot(212, projection='polar')
axn = fig.add_subplot(211, projection='polar')
dvar = 'SOUTH_POLAR_GEOGRAPHIC_LONGITUDE'
lvar = …
```
=> ENH: DMSP SSUSI EDR-Aurora Instrument

CHANGELOG.md, pysatNASA/instruments/cnofs_ivm.py, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/cnofs_vefi.py, pysatNASA/instruments/de2_lang.py, pysatNASA/instruments/de2_nacs.py, pysatNASA/instruments/de2_rpa.py, pysatNASA/instruments/de2_wats.py, pysatNASA/instruments/dmsp_ssusi.py, pysatNASA/instruments/formosat1_ivm.py, pysatNASA/instruments/jpl_gps.py
Addresses #149
Moves `properties` to be the first item under each module docstring.
Inspection.
* Operating system: Mac OS X Monterrey
* Version number: Python 3.10.8
=> STY: docstrings

CHANGELOG.md, README.md, requirements.txt
Addresses #133
Removes the version cap for xarray.  RuntimeError bugs from 2022.11 have been removed in later versions.
Via github actions.
=> MAINT: remove version cap for xarray

.github/workflows/main.yml, CHANGELOG.md, README.md, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/tests/test_instruments.py, requirements.txt
Addresses #142 
pysatCDF has known issues with numpy>= 1.24 (see https://github.com/pysat/pysatCDF/issues/46).  Since this is an optional install, the test behavior here is altered so that a package-wide version cap for numpy is not required.
- Updates GA tests to only use `pysatCDF` install for NEP29 tests (currently set to numpy 1.21)
- Includes logic in test_instruments so that additional load tests with `cdflib` are only run when `pysatCDF` is correctly installed. (The default behavior of the load routines is to use `pysatCDF` if possible, then fall back to `cdflib`, unless specified by the `use_cdflib` kwarg)
- Removes the additional tests for xarray instruments, which are only supported by `cdflib`.
NOTE: this is required before #155 can be tested.
- Bug fix (non-breaking change …
=> BUG/TST: update test behavior in the absence/presence of pysatCDF

CHANGELOG.md, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/methods/_cdf.py
A number of metadata values are dropped where the type is not a float.  This updates the standards so that both int and float are accepted by default.  See https://github.com/pysat/pysat/pull/1108
Tested by running tests with both pysat `main` and https://github.com/pysat/pysat/pull/1108 and inspecting warning messages.
=> BUG: default label types

CHANGELOG.md, pysatNASA/instruments/ace_epam_l2.py, pysatNASA/instruments/ace_mag_l2.py, pysatNASA/instruments/ace_sis_l2.py, pysatNASA/instruments/ace_swepam_l2.py, pysatNASA/instruments/igs_gps.py, pysatNASA/instruments/jpl_gps.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/timed_saber.py, pysatNASA/instruments/timed_see.py
Addresses #174
TIMED SABER has an extra variable for time, for use with the tpaltitude profiles.  This means that 'Epoch' will not be renamed 'time', breaking the new expand_dims code in pysat 3.1.0.
BONUS BUG: when multiple xarray files are combined via `xr.combine_nested`, the attrs for each variable are dropped, meaning that meta is not set for each variable.  
- Renames the profile time variable as 'tp_time', fixing the bug.
- `xr.combine_nested` now uses the kwarg `combine_attrs='override'` to use the attrs from the first file.
- Uses the kwarg `use_cdflib=True` for xarray objects to suppress warning message.  pysatCDF does not currently support xarray, so this can be hard wired
Loading a day of data and inspecting the metadata. …
=> BUG: TIMED SABER and xarray

CHANGELOG.md, README.md, docs/installation.rst, pyproject.toml, pysatNASA/instruments/ses14_gold.py, requirements.txt
Addresses #165
Adds a minimum version of pysat 3.1.0.  Cleans up the GOLD try except notation that was a temporary workaround since it required new pysat features.
***EDIT***: adds a temporary version cap for cdflib to allow the chain of bug fixes for pysat 3.1.0 to move forward while the breaking changes in cdflib 1.0+ are sorted.  See #179 
Github Actions
=> MAINT: pysat 3.1.0 limitation, clean up GOLD code, cdflib version cap

CHANGELOG.md, pysatNASA/instruments/methods/cdaweb.py
Addresses #172
When downloading numerous small files in close proximity to the data servers, sometimes the default code will return an excessive server request error.  This adds a brief pause after each download to avoid erroring.
Running unit tests at locations where this issue arises.
* Version number: python 3.10
* Physically near the servers
=> BUG: excessive download requests

pysatNASA/instruments/dmsp_ssusi.py, pysatNASA/instruments/methods/jhuapl.py, pysatNASA/instruments/timed_guvi.py
Passes the `strict_dim_check` kwarg through the load routines for auroral imager data in jhuapl methods.  Follows the convention for use_cdflib in that the default option raises warnings if new instruments are added with this routine, but existing instruments that are understood suppress the warning.
Loading data for dmsp ssusi and timed guvi.  Also inspecting the logs in GA.
* Version number: python 3.9.7
* Requires pysat 3.1.0
- [na] Add a note to ``CHANGELOG.md``, summarizing the changes -- ***instruments affected are new to this version***
=> ENH: strict_dim_check kwarg and jhuapl load routines

CHANGELOG.md, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/tests/test_methods_cdaweb.py
Addresses #166 
pysat style is updating data_path to be input as an arg, not a kwarg. Affects download, etc.
So the download functions in the cdaweb methods have been updated accordingly
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration
- local pytest with python 3.9
* Operating system: [Mac OS 13.4]
* Version number: [Python 3.9]
* Conda environment
=> Data path arg

pysatNASA/instruments/ace_epam_l2.py, pysatNASA/instruments/ace_mag_l2.py, pysatNASA/instruments/ace_sis_l2.py, pysatNASA/instruments/ace_swepam_l2.py, pysatNASA/instruments/methods/_cdf.py, pysatNASA/instruments/methods/ace.py, pysatNASA/instruments/methods/cdaweb.py
Addresses #186
Creates a custom load routine for ACE data products.  Data is loaded as xarray, then extra dimensions (labels for string time values) are dropped.
- epam and swepam converted to pandas DataFrame after extra dimensions are dropped
- Updates label types to match pysat standards `(float, int, str)`
- Changes directly applied since ACE instruments are not released in a previous version
- Fixed a bug where the ACE clean routine was trying to apply fill vals to coords
Using the workflow in #186 and checking the metadata
* Version number: python 3.10.9
=> BUG/ENH: ACE Meta data and unused time dimensions

CHANGELOG.md, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/icon_mighti.py, pysatNASA/instruments/methods/jhuapl.py, pysatNASA/instruments/ses14_gold.py
Addresses #189
Specifies a default for `decode_times` to maintain current behavior.
Loading data for xarray netCDF instruments
* Version number: Python 3.10.9
=> MAINT: decode times kwarg

.readthedocs.yml, CHANGELOG.md, docs/requirements.txt, pyproject.toml
Use pip install with options so that a separate requirements list under the docs directory is not needed.
Also adds a minimum version to `sphinx_rtd_theme`. Somewhere in the dependency tree, someone updated something which is breaking pip's ability to calculate what the dependencies are. Forcing a minimum version of the rtd theme fixes this (for now).
via GitHub Actions
=> MAINT: update installs for RTD

CHANGELOG.md, pysatNASA/instruments/methods/general.py
The maven insitu data is having an issue with the general cleaning routine. This is because it includes transformation matrics that have symmetric dimensions, ie ('time', 'compno_3', 'compno_3'). `xarray` doesn't like this. Since it doesn't make sense to clean the transformation matrices (similar to coords), we place a check in the clean routine to skip over these.
loading maven insitu data
=> BUG: cleaning routine

CHANGELOG.md, pysatNASA/instruments/formosat1_ivm.py, pysatNASA/instruments/iss_fpmu.py, pysatNASA/instruments/methods/__init__.py, pysatNASA/instruments/methods/formosat.py, pysatNASA/instruments/methods/iss.py, pysatNASA/instruments/methods/omni.py, pysatNASA/instruments/omni_hro.py
Addresses #121
- Moves acknowledgement string and references to methods files for all (non-deprecated) instruments.
- Uses standard `init` routine for other methods
- Updates references for new calibration of ISS FPMU data
Instantiating instruments and printing refs:
```
import pysat
fpmu = pysat.Instrument('iss', 'fpmu')
print(fpmu.references)
```
=> STY: use standard init routines

CHANGELOG.md, README.md, docs/installation.rst, pyproject.toml, pysatNASA/instruments/methods/omni.py, pysatNASA/tests/test_omni_hro.py
Addresses #34
- Tests remaining omni custom methods.
- Adds a version minimum for scipy.
- Fixed a bug in `calculate_imf_steadiness`, new window was calculated as float, incurring the wrath of pandas 🐼 
new unit tests
=> TST: routines for omni

CHANGELOG.md, docs/supported_instruments.rst, pysatNASA/instruments/__init__.py, pysatNASA/instruments/methods/__init__.py, pysatNASA/instruments/methods/formosat.py, pysatNASA/instruments/methods/igs.py, pysatNASA/instruments/methods/iss.py, pysatNASA/instruments/methods/reach.py, pysatNASA/instruments/reach_dosimeter.py
- Adds reach dosimeter data
- Fixes docstring copy paste issues
```
import pysat
reach = pysat.Instrument(inst_module=pysatNASA.instruments.reach_dosimeter, inst_id='101')
reach.remote_file_list()
reach.download(dt.datetime(2017, 4, 10))
reach.load(date=dt.datetime(2017, 4, 10))
reach.data
```
* Operating system: Ventura
* Version number: Python 3.9.12
=> ENH: REACH data

CHANGELOG.md, pysatNASA/__init__.py
On another project, I found out that `metadata` needs to be imported from `importlib` and can't be reliably called as a submodule by importing `importlib`.  Added fixes here.
`python -c "import pysatNASA; print(pysatNASA.__version__)"`
But sometimes this also works without the fix 🐞 
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant
=> Improved init

.github/workflows/main.yml, CHANGELOG.md, pysatNASA/instruments/cnofs_vefi.py
C/NOFS VEFI `dc_b` data has an updated dataset (v6) uploaded to SPDF as of 7 Nov 2023. This does not use the old error flag, but uses the standard fill value demarked in metadata. Since 'B_flag' is no longer present, unit tests will fail unless this is fixed.
Updates to use the standard cleaning routine
```
import pysat
vefi = pysat.Instrument('cnofs', 'vefi', tag='dc_b')
vefi.download(dt.datetime(2009, 1, 1))
vefi.load(2009, 1)
print(vefi.meta['B_north'].fill)
vefi = pysat.Instrument('cnofs', 'vefi', tag='dc_b', clean_level='none')
vefi.load(2009, 1)
print(vefi.meta['B_north'].fill)
```
Verify that for the clean routine the fill value is NaN, and for the non-clean load the fill value is -1e+31
**Test …
=> MAINT: cnofs vefi magnetometer data

.github/workflows/pysat_rc.yml, CHANGELOG.md, pyproject.toml, pysatNASA/instruments/cnofs_plp.py, pysatNASA/instruments/icon_euv.py, pysatNASA/instruments/icon_ivm.py, pysatNASA/instruments/maven_insitu_kp.py, pysatNASA/instruments/methods/_cdf.py, pysatNASA/instruments/methods/cdaweb.py, pysatNASA/instruments/timed_guvi.py, pysatNASA/instruments/timed_saber.py
Addresses #218 (partial)
Fixes a major issue where `cdasws` ignores the end date for download requests if no data is present at 00:00:00 on the end date. This fixes most of the items in #218.
Adds testing flags for upcoming pysat pull to ignore "new" tests for now while we update the ecosystem. Usage of flags includes TODO statements linked to the relevant issue.
Turns on tests for ICON IVM-B now that some data is public for that.
pytest using the `enh/test_triage` branch of `pysat`
* Operating system: Ventura 3.6.1
* Version number: Python 3.10.9
* `pysat` enh/test_triage branch
If this is a release PR, replace the first item of the above checklist …
=> BUG/MAINT: cdaweb downloads, ICON IVM-B tests, new flag to skip new tests

.github/workflows/main.yml, .zenodo.json, CHANGELOG.md, pyproject.toml, pysatNASA/instruments/dmsp_ssusi.py, pysatNASA/instruments/icon_fuv.py, pysatNASA/instruments/maven_sep.py, pysatNASA/instruments/timed_guvi.py
- Updates NEP29 standards for Apr 5, 2024.
- Updates zenodo -> author order, institutions, keywords
via GitHub Actions main.yml
=> MAINT: NEP29 Apr 2024, zenodo updates

CHANGELOG.md, pysatNASA/instruments/methods/cdaweb.py
Addresses the presence of an error being raised when no remote files are found, instead of an empty list.
```
import pysat
stime = dt.datetime(2024, 1, 1)
etime = dt.datetime(2024, 2, 1)
out_list = pysatNASA.instruments.methods.cdaweb.cdas_list_remote_files(tag='sdr-disk', inst_id='f18', start=stime, stop=etime, supported_tags=pysatNASA.instruments.dmsp_ssusi.download_tags, series_out=False)
out_series = pysatNASA.instruments.methods.cdaweb.cdas_list_remote_files(tag='sdr-disk', inst_id='f18', start=stime, stop=etime, supported_tags=pysatNASA.instruments.dmsp_ssusi.download_tags, series_out=True)
```
Note, there *is* data for this instrument and time, …
=> Empty return without remote files

.github/workflows/main.yml, .zenodo.json, CHANGELOG.md, pysatNASA/instruments/cnofs_vefi.py, requirements.txt
Addresses #232
Coveralls was not producing a report for MacOS using the coverallsapp integration. The coveralls integration has been switched to the GitHub service in the case of MacOS runs. 
* Operating system: GitHub Actions MacOS
* Version number: Python 3.11 and Python 3.12
=> BUG: Revert integration to GitHub service for coveralls on MacOS

CHANGELOG.md, pysatNASA/instruments/dmsp_ssusi.py, pysatNASA/instruments/methods/dmsp.py, pysatNASA/instruments/reach_dosimeter.py, pysatNASA/instruments/ses14_gold.py, pysatNASA/tests/test_instruments.py
Addresses #239 by adding file handing for the change in file format across a specific date.
```
import pysat
ssusi = pysat.Instrument(inst_module=pysatNASA.instruments.dmsp_ssusi, tag='sdr-disk', inst_id='f18')
stime = dt.datetime(2023, 3, 20)
etime = dt.datetime(2023, 3, 25)
ssusi.download(start=stime, stop=etime)
ssusi.files.files
```
Yields:
```
2023-03-20 00:53:14    dmspf18_ssusi_sdr-disk_2023079T005314-2023079T...
2023-03-20 12:06:22    dmspf18_ssusi_sdr-disk_2023079T120622-2023079T...
2023-03-20 12:46:42 …
```
=> Fix DMSP SSUSI file format change

.github/workflows/main.yml, .github/workflows/pysat_rc.yml, CHANGELOG.md, pyproject.toml
Updates to use the coveralls app, streamline the usage.
via GitHub Actions
=> MAINT: use coveralls app

.github/workflows/main.yml, pysatNASA/instruments/methods/cdaweb.py
Addresses #242 (partial)
Ensures backward compatibility with pandas<2.2 and forward compatibility with pandas 3.0.
via pytest
* Operating system: Sonoma 14.6.1
* Version number: Python 3.11.5
* pandas 2.1.4
=> MAINT: ensure backward compat with pandas

.github/workflows/main.yml, CHANGELOG.md
Updates ops environment tests to use python 3.9. 
Code still supports 3.6, but there is no way of testing this. A partial list of things to do to update the code is documented in #245.
GitHub Actions
- [rc] Make sure you are merging into the ``develop`` (not ``main``) branch
=> MAINT: cycle ops tests
